config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#home'

  get 'booking', to: 'static_pages#booking'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'pricing', to: 'static_pages#pricing'
  get 'benefits', to: 'static_pages#benefits'
  get 'gallery', to: 'static_pages#gallery'

  get 'static_pages/sign_up'

  resources :appointments
  get 'new_appointment', to: 'appointments#new'
  get 'pre_new_appointment', to: 'appointments#pre_new'
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
before_action :authenticate_user!
  def new
    @hour = flash[:hour]
    puts @hour
  end

  def pre_new
    flash[:hour] = params[:hour]
    puts session[current_user]
    redirect_to new_appointment_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private

  	def sign_up_params
    	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  	end

  	def account_update_params
    	params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def booking
  	@date = Date.today
    @week = (@date.beginning_of_week..@date.end_of_week).to_a
    @days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    @times = ["10:00AM","12:00PM","1:00PM","2:00PM","3:00PM","4:00PM"]
    @option = params[:option]
  end

  def sign_up
  end

  def about
  end

  def pricing
  end

  def contact
  end

  def benefits
  end

  def gallery
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/appointments/index.html.erb
<%= @new_dates %>

app/views/appointments/new.html.erb
<% if @hour.to_i > 12 %>
	<% @adjusted_hour = @hour.to_i - 12 %>
<% else %>
	<% @adjusted_hour = @hour %>
<% end %>
<h1 style="text-align:center">Scheduling an appointment for:</h1>
<h2 style="text-align:center"><%=@cday%> <%=@adjusted_hour%>:00 <%=(@hour.to_i > 12) ? 'PM' : 'AM' %> </h2>
<div class="row">
	<form class="col-md-4 col-centered">
	  <div class="form-group">
	    <label for="first_name">First Name</label>
	    <input type="string" class="form-control" id="first_name" value=<%=current_user.first_name%>>
	  </div>
	  <div class="form-group">
	    <label for="last_name">Last Name</label>
	    <input type="string" class="form-control" id="last_name" value=<%=current_user.last_name%>>
	  </div>
	  <div class="form-group">
	    <label for="email">Email</label>
	    <input type="email" class="form-control" id="eemail" value=<%= current_user.email %>>
	  </div>

	  <button type="submit" class="btn btn-default submit">Reserve Your Spot!</button>
	  <script>
	  	
	  </script>
	</form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloom Wellness</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-custom" style="height: 60px; padding: 0 150px 0 150px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" style="margin-top: 4px;" href=<%= root_path %>><%= image_tag('bloom_wellness.png', height: '45', width: '100', class: "logo")%></a>
      <button type="button" class="navbar-toggle collapsed menu-button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-menu-hamburger"></span>
      </button> 
    </div>
    <ul class="nav navbar-nav navbar-collapse collapse" id="navbar" style="float: right;">
      <li><%= link_to 'HOME', '/',{:style=>'color:#A8A8A8;'} %></li>
      <li><%= link_to 'ABOUT US', about_path, {:style=>'color:#A8A8A8;'} %></li>
      <li><%= link_to 'PACKAGES & PRICING', pricing_path, {:style=>'color:#A8A8A8;'} %></li>
      <li><%= link_to 'BOOKING', booking_path(option: "float1"), {:style=>'color:#A8A8A8;'} %></li>
      <li><%= link_to 'GALLERY', gallery_path, {:style=>'color:#A8A8A8;'} %></li>
      <li><%= link_to 'BENEFITS', benefits_path, {:style=>'color:#A8A8A8;'} %></li>
      <li><%= link_to 'CONTACT', contact_path, {:style=>'color:#A8A8A8;'} %></li>
    </ul>
  </div>
</div>

<div style="text-align:center">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div style="margin-bottom: 150px;">
  <%= yield %>
</div>

<footer class="navbar navbar-inverse navbar-bottom" style="margin-bottom:0px; text-align:center; margin-top: 50px;">
  <div class="btn-group-lg" style="margin-top:20px; margin-bottom:20px;">
    <button type="button" class="btn btn-default social-button">
          <i class="icon-fa-facebook"></i> 
    </button>
    <button type="button" class="btn btn-default social-button">
          <i class="icon-fa-twitter"></i> 
    </button>
    <button type="button" class="btn btn-default social-button">
          <i class="icon-fa-instagram"></i> 
    </button>
    <button type="button" class="btn btn-default social-button">
          <i class="icon-fa-youtube"></i> 
    </button>
  </div>
</footer>

</body>
</html>

app/views/static_pages/about.html.erb
<h1 style="text-align:center;">About Bloom</h1>
<p style="text-align:center;">Bloom description.</p>

app/views/static_pages/benefits.html.erb
  <div class="absolute-container">
  	<img class="mural" src=<%=image_path('float_tank.jpg')%> alt="Float Tank"/>
    <div class="mural-text-center">
      <p>WHAT IS FLOATING</p>
    </div>
  </div>

 <div class="description">
  	 <br>
     <h3><small>
     Floating is the practice of lying in 10 inches of water in a large, cozy, and luxurious tub. Inside the tub, there is 1000 pounds of Epsom salt, which completely supports your body allowing you to naturally float. Your eyes will be submerged in water, but your face is above the water. The water is the same temperature as your skin, which gives you the sensation of floating in air. You lose the effects and perception of gravity. The environment is pitch black, soundproofed, with a neutral smell. As a result, the floater enters a deep state of mental and physical relaxation.
     </small></h3>
  </div>

   <div class="absolute-container">
  	<img class="mural" src=<%=image_path('float_tank_2.jpg')%> alt="Float Tank"/>
    <div class="mural-text-center">
      <p>BENEFITS</p>
    </div>
  </div>

<div class="description">
  <div class="row">
    <div class="col-md-2">
      <img src=<%=image_path 'sleep.jpg'%> alt="..." class="img-circle border-circle" height="150" width="150"/>
    </div>
    <div class="col-md-4">
      <h3 style="text-align: left;">SLEEP</h3>
      <p style="text-align: left;">
        Floating can help you reclaim your night and remind yourself how great your sleep can be. It is an effective treatment for people with insomnia and other sleep issues.
      </p>
    </div>
    <div class="col-md-2">
      <img src=<%=image_path 'pain.jpg'%> alt="..." class="img-circle border-circle" height="150" width="150"/>
    </div>
    <div class="col-md-4">
      <h3 style="text-align: left;">PAIN</h3>
      <p style="text-align: left";>
        The salt water minimizes the force of gravity on your body. This allows for your muscles, tendons, ligaments to relax, while your back decompresses into its ideal position. Research suggests floating can help with chronic pain, back pain, and other maladies.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <img src=<%=image_path 'beauty.jpg'%> alt="..." class="img-circle border-circle" height="150" width="150"/>
    </div>
    <div class="col-md-4">
      <h3 style="text-align: left;">BEAUTY</h3>
      <p style="text-align: left;">
        Float tanks contain 1000 pounds of salt, which is great for hydrating the skin. Our tank has a Microsilk unit which generates creating millions of bubbles small enough to penetrate the pores of your skin. The tiny oxygen bubbles, and salt form a powerful team that leaves your skin silky smooth and irresistibly soft.
      </p>
    </div>
    <div class="col-md-2">
      <img src=<%=image_path 'meditation.jpg'%> alt="..." class="img-circle border-circle" height="150" width="150"/>
    </div>
    <div class="col-md-4">
      <h3 style="text-align: left;">MEDITATION</h3>
      <p style="text-align: left";>
        Hack your soul and streamline the bliss. Meditation maybe difficult for some, but floating makes it a lot easier. By eliminating distractions, floating helps you master your meditative process.
      </p>
    </div>
  </div>
</div>

app/views/static_pages/booking.html.erb
<!--<script>
$(document).ready(function(){
	$(window).scroll(function(){
    	$("#week-selector").css("top", Math.max(0, 50 - $(this).scrollTop()));
    	alert("Test");
	});
}
</script>-->
<script>
	$(window).scroll(function(){
    	//$("#week-top").css("margin-top",Math.max(20,20-$(this).scrollTop()));
    	//alert($("#week-top").css("height"));
    	/*if ($(window).scrollTop() > 5) {
            $("#week-top").css({
                position: 'absolute',
                top: 0
            });        } 
        else {
            $("#week-top").css({
                position: 'static'
            });
        }*/
	});
</script>
<script src="jquery.js"></script>
<script src="jquery.sticky.js"></script>
<script>
  $(document).ready(function(){
    $("#week-top").sticky({topSpacing:50});
  });
</script>

<div class="container" style="text-align: center;">
	<div class="calendar">
		<div id="week-top">
			<div id="week-selector">
				<a href="#"><span class="glyphicon glyphicon-chevron-left"></span></a>
				<div style="font-size: 0.8em; display: inline-block;">This Week, <%= @date.strftime("%b %Y")%></div>
				<a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
			<ul class="weekdays">
				<% for i in 0..6 %>
					<li>
						<h3><small><strong><%= @days[i] %></strong></small></h3>
						<% if @week[i].today? %>
							<h4><strong><u><%= @week[i].strftime("%e") %></u></strong></h4>
							<!--Wrong Date-->
						<% else %>
							<h4><strong><%= @week[i].strftime("%e") %></strong></h4>
						<% end %>
					</li>
				<%end%>
			</ul>
		</div>
		<div id="weekday-container">
			<ul class="weekdays" id="times">
				<% for i in 0..6 %>
					<li id="day-column">
						<% for j in 0..5 %>
							<div id="time-slot">
								<!--Need to fix darker borders-->
								<br/>
								<h4 style="text-align: left; padding-left: 10%;"><small><%= @times[j] %></small></h4>
								<br/>
								<button type="button" class="btn btn-default btn-bloom">Reserve</button>
							</div>
						<% end %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>


<!--<h1 style="text-align:left; padding-left: 200px; float:left;">BOOK NOW!</h1>
  <% #Initialize the proper date and week, can be simpler using step %>
  <% @sunday = @date.day - @date.wday %>
  <% @saturday = @sunday + 6 %>
  <% @beginning_month = @date.month %>
  <% @ending_month = @date.month %>
  <% @beginning_year = @date.year %>
  <% @ending_year = @date.year %>
  <% if @sunday < 1 %>
  	<% @beginning_month = @date.month-1%>
  	<% if @beginning_month < 1 %>
  		<% @beginning_year-=1 %>
  		<% @beginning_month = 12 %>
  	<% end %>
  	<% @sunday+=Time.days_in_month(@beginning_month,@date.year) %>
  <% end %>
  <% if @saturday > Time.days_in_month(@date.month,@date.year) %>
  	<% @ending_month = @date.month+1%>
  	<% if @ending_month > 12 %>
  		<% @ending_year+=1 %>
  		<% @ending_month = 1 %>
  	<% end %>
  	<% @saturday-=Time.days_in_month(@date.month,@date.year) %>
  <% end %>
  <% @beginning_of_week = Date.civil(@beginning_year, @beginning_month, @sunday) %>
  <% @end_of_week = Date.civil(@ending_year, @ending_month, @saturday) %>

<ul class="nav nav-pills" style="text-align:right; float:right; padding-right: 160px; margin-top: 20px;">
  <li role="presentation" class= "<%= 'active' if current_page?(booking_path(option: "float1")) %>" ><%= link_to 'Float 1', booking_path(option: 'float1') %></li>
  <li role="presentation" class= "<%= 'active' if current_page?(booking_path(option: "float2")) %>" ><%= link_to 'Float 2', booking_path(option: 'float2') %></li>
  <li role="presentation" class= "<%= 'active' if current_page?(booking_path(option: "chair")) %>" ><%= link_to 'Chair', booking_path(option: 'chair') %></li>
  <li role="presentation" class= "<%= 'active' if current_page?(booking_path(option: "yoga")) %>"><%= link_to 'Yoga', booking_path(option: 'yoga') %></li>
</ul>

<% #Set up table %>
<table id='calendar' align="center">
	<tr>
		<% (@beginning_of_week..@end_of_week).each do |d| %>
			<th><%= d.strftime('%A') %></th>
		<% end %>
  	</tr>
  	<tr>
  		<% (@beginning_of_week..@end_of_week).each do |d| %>
			<th><%= d.strftime('%B %e, %Y') %></th>
			<% @cday = d.strftime('%B %e, %Y') %>
		<% end %>
	</tr>
	<tr>
		<% (10..18).each do |i| %>
			<tr>
			  	<% 7.times do %>
			    	<td> 
			    		<div class="date-block">
			    			<p>
			    				<div>
			    					<p style="font-size:12px; margin-bottom:-3px; padding-top: 40px;"> 
			    						<% if i > 12 %>
			    							<%= i-12 %>:00 PM
			    						<% else %>
			    							<%= i %>:00 AM
			    						<% end %>
			    					</p>
			    					<p>
			    						<b>Available</b>
			    					</p>
			    				</div>
			    				<div class="date-button">
				    				<a class="btn btn-info" href=<%=pre_new_appointment_path(hour: i, month: @date.month, day: @date.day, year: @date.year, cday: @cday, option: @option)%> role="button">Reserve</a>
									</button>
								</div>
			    			</p>
			    		</div>
			    	</td>
			  	<% end %>
		  	</tr>
		<% end %>
	</tr>
</table>-->

app/views/static_pages/contact.html.erb
<h1 style="text-align:center;">Contact Us</h1>
<p style="text-align:center;">Contact Info.</p>

app/views/static_pages/gallery.html.erb
<h1 style="text-align:center;">Gallery</h1>
<p style="text-align:center;">Pictures here.</p>

app/views/static_pages/home.html.erb
<div class="container-fluid">
  <div id="home-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#home-carousel" data-slide-to="0" class="active"></li>
      <li data-target="#home-carousel" data-slide-to="1"></li>
      <li data-target="#home-carousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img class="mural" src=<%=image_path('float_tank.jpg')%> alt="Float 	Tank"/>
        <div class="carousel-caption mural-text">
  			 <!--<button type="button" class="btn btn-primary btn-xlarge">
  				  BOOK NOW
  			 </button>-->
         <h3>Bloom Wellness is a wellness center for the 21st century. 
         <br/>
         <br/>
         We help you claim total immersion in the moment using tomorrow's technologies, a clean environment, and a beautiful space. 
         <br/>
         <br/>
         Discover your path at Bloom Wellness.</h3>
        </div>
      </div>
      <div class="item">
        <img class="mural" src=<%=image_path('float_tank_3.jpg')%> alt="Float Tank"/>
        <div class="carousel-caption mural-text">
         <!--<button type="button" class="btn btn-primary btn-xlarge">
            BOOK NOW
         </button>-->
         <h3>Bloom Wellness is a wellness center for the 21st century. 
         <br/>
         <br/>
         We help you claim total immersion in the moment using tomorrow's technologies, a clean environment, and a beautiful space. 
         <br/>
         <br/>
         Discover your path at Bloom Wellness.</h3>
        </div>
      </div>
      <div class="item">
        <img class="mural" src=<%=image_path('float_tank_4.jpg')%> alt="Float Tank"/>
        <div class="carousel-caption mural-text">
         <!--<button type="button" class="btn btn-primary btn-xlarge">
            BOOK NOW
         </button>-->
         <h3>Bloom Wellness is a wellness center for the 21st century. 
         <br/>
         <br/>
         We help you claim total immersion in the moment using tomorrow's technologies, a clean environment, and a beautiful space. 
         <br/>
         <br/>
         Discover your path at Bloom Wellness.</h3>
        </div>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#home-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#home-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="description">
  	 <br>
     <h3><small>
     Floating is the practice of lying in 10 inches of water in a large, cozy, and luxurious tub. Inside the tub, there is 1000 pounds of Epsom salt, which completely supports your body allowing you to naturally float. Your eyes will be submerged in water, but your face is above the water. The water is the same temperature as your skin, which gives you the sensation of floating in air. You lose the effects and perception of gravity. The environment is pitch black, soundproofed, with a neutral smell. As a result, the floater enters a deep state of mental and physical relaxation.
     </small></h3>
  </div>

  <div class="absolute-container">
  	<div class="embed-responsive embed-responsive-16by9 mural">
  	  	<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/NOwx2uQTQQU"></iframe>
  	</div>
  </div>

  <p class="description">
  	Video description goes here.
  </p>

  <div class="absolute-container">
  	<img class="mural" src=<%=image_path('dreamwave.jpg')%> alt="Dream Wave"/>
  	<!--<div class="mural-text">
  		<button type="button" class="btn btn-primary btn-xlarge">
  			BOOK NOW
  		</button>
  	</div>-->
  </div>

  <p class="description">
  	DreamWave description goes here.
  </p>

  <div class="absolute-container">
  	<img class="mural" src=<%=image_path('float_tank_2.jpg')%> alt="Float Tank"/>
    <!--<div class="mural-text">
      <button type="button" class="btn btn-primary btn-xlarge">
        BOOK NOW
      </button>
    </div>-->
  </div>

  <div class="jumbotron">
    <p>Mission statement.</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
  </div>
</div>

app/views/static_pages/pricing.html.erb
<div class="container" style="width: 60%;">
	<h1 style="text-align:center;">Pricing & Packages</h1>

	<table class="table table-bordered table-condensed" id="pricing-table">
		<tr>
			<td style="vertical-align: middle;"><%=image_tag('bloom_wellness.png', height: 'auto', width: '100%')%></td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>1 Float</h2>
				<p class="lead" style="margin-top:-10px;">$89</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>3 Float</h2>
				<p class="lead" style="margin-top:-10px;">$149</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>10 Float</h2>
				<p class="lead" style="margin-top:-10px;">$449</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
		</tr>
		<tr>
			<td style="vertical-align: middle; margin: auto;"><%=image_tag('morpheus.png', height: '175px', width: '100%')%></td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>15 Minutes</h2>
				<p class="lead" style="margin-top:-10px;">$20</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>30 Minutes</h2>
				<p class="lead" style="margin-top:-10px;">$30</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>1 Hour</h2>
				<p class="lead" style="margin-top:-10px;">$45</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
		</tr>
		<tr>
			<td style="vertical-align: middle; margin: auto;"><%=image_tag('sauna.png', height: 'auto', width: '100%')%></td>
			<td class="price-block" style="padding-left: 30px;">
				<h2>10 Minutes</h2>
				<p class="lead" style="margin-top:-10px;">$15</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
			<td class="price-block" style="padding-left: 30px;">
				<h3>20 Minutes Deluxe</h3>
				<p class="lead" style="margin-top:-10px;">$20</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
			<td class="price-block" style="padding-left: 30px;">
				<h3>40 Minutes Deluxe</h3>
				<p class="lead" style="margin-top:-10px;">$30</p>
				<button type="button" class="btn btn-default price-button">select</button>
			</td>
		</tr>
	</table>
</div>

app/views/static_pages/sign_up.html.erb
<h1>StaticPages#sign_up</h1>
<p>Find me in app/views/static_pages/sign_up.html.erb</p>